// src/components/ui/PageHeader.tsx
export function PageHeader({
  title,
  eyebrow,
  action,
}: {
  title: string;
  eyebrow?: string;
  action?: React.ReactNode;
}) {
  return (
    <header className="flex items-end justify-between gap-3 pb-1">
      <div className="min-w-0">
        {eyebrow ? (
          <p className="label-eyebrow text-[0.625rem] text-bronze">{eyebrow}</p>
        ) : null}
        <h1 className="truncate font-display text-2xl font-semibold tracking-tight">
          {title}
        </h1>
      </div>
      {action ? <div className="shrink-0">{action}</div> : null}
    </header>
  );
}

// frontend/src/components/ui/PageHeader.vue
<script setup lang="ts">
defineProps<{ eyebrow?: string; title: string }>();
</script>

<template>
  <header class="flex items-end justify-between gap-3">
    <div>
      <p v-if="eyebrow" class="label-eyebrow text-[0.625rem] text-faint">{{ eyebrow }}</p>
      <h1 class="font-display text-2xl font-semibold tracking-tight">{{ title }}</h1>
    </div>
    <div class="shrink-0">
      <slot name="action" />
    </div>
  </header>
</template>
