// src/components/ui/StatTile.tsx
import { cn } from "@/lib/utils";

/**
 * A single headline figure. The `accent` variant fills bronze and is reserved for
 * the one most important number on a screen, so the eye has a clear anchor (we
 * deliberately avoid a grid of identical-weight tiles).
 */
export function StatTile({
  label,
  value,
  sub,
  accent = false,
  className,
}: {
  label: string;
  value: React.ReactNode;
  sub?: React.ReactNode;
  accent?: boolean;
  className?: string;
}) {
  return (
    <div
      className={cn(
        "rounded-2xl border p-4 shadow-soft",
        accent
          ? "border-transparent bg-bronze text-bronze-ink"
          : "border-line bg-surface",
        className,
      )}
    >
      <p
        className={cn(
          "label-eyebrow text-[0.625rem]",
          accent ? "text-bronze-ink/70" : "text-faint",
        )}
      >
        {label}
      </p>
      <p className="mt-1 font-display text-3xl font-semibold tracking-tight tnum">
        {value}
      </p>
      {sub ? (
        <p className={cn("mt-0.5 text-sm", accent ? "text-bronze-ink/80" : "text-muted")}>
          {sub}
        </p>
      ) : null}
    </div>
  );
}

// frontend/src/components/ui/StatTile.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    label: string;
    value: string | number;
    sub?: string;
    accent?: boolean;
  }>(),
  { accent: false },
);
</script>

<template>
  <div
    class="rounded-2xl border p-4"
    :class="
      accent
        ? 'border-bronze/30 bg-bronze/10'
        : 'border-line bg-surface shadow-[var(--shadow-soft)]'
    "
  >
    <p class="label-eyebrow text-[0.625rem]" :class="accent ? 'text-bronze' : 'text-faint'">
      {{ label }}
    </p>
    <p class="mt-1 font-display text-3xl font-semibold tnum" :class="accent ? 'text-bronze' : 'text-fg'">
      {{ value }}
    </p>
    <p v-if="sub" class="mt-0.5 text-xs text-muted">{{ sub }}</p>
  </div>
</template>
