// frontend/src/components/ui/Avatar.vue
<script setup lang="ts">
import { computed } from "vue";
import { initials } from "@/lib/format";
const props = defineProps<{ name: string }>();
const text = computed(() => initials(props.name));
</script>

<template>
  <span
    class="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-elevated font-display text-sm font-semibold text-muted"
  >
    {{ text }}
  </span>
</template>

// src/components/ui/Avatar.tsx
import { cn } from "@/lib/utils";
import { initials } from "@/lib/utils";

export function Avatar({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  return (
    <span
      className={cn(
        "inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-full border border-line bg-elevated font-display text-sm font-semibold text-muted",
        className,
      )}
      aria-hidden
    >
      {initials(name) || "?"}
    </span>
  );
}
