// frontend/src/components/ui/EmptyState.vue
<script setup lang="ts">
import type { Component } from "vue";
defineProps<{ icon?: Component; title: string; description?: string }>();
</script>

<template>
  <div
    class="flex flex-col items-center gap-3 rounded-2xl border border-dashed border-line px-6 py-10 text-center"
  >
    <component :is="icon" v-if="icon" class="h-8 w-8 text-faint" :stroke-width="1.5" />
    <div>
      <p class="font-medium">{{ title }}</p>
      <p v-if="description" class="mt-1 text-sm text-muted">{{ description }}</p>
    </div>
    <slot />
  </div>
</template>

// src/components/ui/EmptyState.tsx
import type { LucideIcon } from "lucide-react";

export function EmptyState({
  icon: Icon,
  title,
  description,
  action,
}: {
  icon: LucideIcon;
  title: string;
  description?: string;
  action?: React.ReactNode;
}) {
  return (
    <div className="flex flex-col items-center justify-center rounded-2xl border border-dashed border-line px-6 py-12 text-center">
      <div className="mb-3 flex h-12 w-12 items-center justify-center rounded-full bg-elevated text-faint">
        <Icon className="h-6 w-6" strokeWidth={1.75} />
      </div>
      <p className="font-display text-lg font-medium">{title}</p>
      {description ? (
        <p className="mt-1 max-w-xs text-sm text-muted">{description}</p>
      ) : null}
      {action ? <div className="mt-5">{action}</div> : null}
    </div>
  );
}
